# Generated by Django 3.0.3 on 2020-03-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20200323_0700'),
        ('question', '0002_auto_20200323_0700'),
        ('exam', '0002_examquestionnairedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exam.ExamCategory'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exam.ExamLevel'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question.SubTopics'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question.Subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question.Topics'),
        ),
        migrations.AlterField(
            model_name='examquestionnairedetails',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.Exam'),
        ),
        migrations.AlterField(
            model_name='examquestionnairedetails',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.Questionnaire'),
        ),
    ]
