# Generated by Django 3.0.3 on 2020-03-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200322_0556'),
        ('exam', '0003_auto_20200323_0700'),
    ]

    operations = [
    ]
