# Generated by Django 3.0.3 on 2020-03-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200323_0700'),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question.SubTopics'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question.Subject'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question.Topics'),
        ),
        migrations.AlterField(
            model_name='questionnairedetail',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.Question'),
        ),
        migrations.AlterField(
            model_name='questionnairedetail',
            name='questionnaire_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.Questionnaire'),
        ),
    ]
