# Generated by Django 3.0.3 on 2020-03-30 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_merge_20200328_0646'),
        ('questionnaire', '0004_merge_20200325_0949'),
    ]

    operations = [
    ]
