# PROFESSIONAL_STRINGS
PROFESSIONAL_VERBOSE_NAME = 'Professional'
PROFESSIONAL_VERBOSE_NAME_PLURAL = 'Professionals'
# PROFESSIONAL_STRINGS

# LOGIN_STRINGS
LOGIN_CREDENTIAL_BLANK_ERROR = 'Please provide both username and password'
LOGIN_CREDENTIAL_ERROR_MSG = 'Invalid Credentials'
# LOGIN_STRINGS