#DIVISION STRINGs
DIVISION_VERBOSE_NAME = "Division"
DIVISION_VERBOSE_NAME_PLURAL = "Divisions"
#DIVISION STRINGs

#DISTRICT STRINGs
DISTRICT_VERBOSE_NAME = "District"
DISTRICT_VERBOSE_NAME_PLURAL = "Districts"
#DISTRICT STRINGs