QUESTION_STATUS_PUBLISHED_TEXT = 'Published'
QUESTION_STATUS_DRAFT_TEXT = 'Draft'
QUESTION_STATUS_REJECTED_TEXT = 'Rejected'

QUESTION_STATUS_PUBLISHED = '1'
QUESTION_STATUS_DRAFT = '2'
QUESTION_STATUS_REJECTED = '3'


MINIMUM_ANSWER_VALIDATION = 'You Have To Add Atleast Two Answer'
MINIMUM_CORRECT_ANSWER_VALIDATION = 'You Have To Add Atleast One Correct Answer'