# Generated by Django 3.0.3 on 2020-03-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='question.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question.Difficulty', verbose_name='difficulty level'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question.QuestionType', verbose_name='question type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question.SubTopics'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.Subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question.Topics'),
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.Subject'),
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='topics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.Topics'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject', to='question.Subject'),
        ),
    ]
