# Generated by Django 3.0.3 on 2020-04-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_merge_20200330_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
