# Generated by Django 3.0.3 on 2020-03-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_advice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Career_Advice',
            new_name='CareerAdvice',
        ),
    ]
