# Generated by Django 3.0.3 on 2020-03-10 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0002_examquestionnairedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_status', models.CharField(choices=[('1', 'Failed'), ('2', 'Pending'), ('3', 'Passed')], default=2, max_length=100)),
                ('percentage_of_correct', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=250)),
                ('exam_submitted_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_registration', to='exam.Exam')),
                ('professional', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_exam_registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'registration',
                'db_table': 'registration',
            },
        ),
    ]
