# Generated by Django 3.0.3 on 2020-03-23 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200323_0700'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='exam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_registration', to='exam.Exam'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='professional',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_exam_registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
