# Generated by Django 2.2.4 on 2019-10-15 05:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '__first__'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exampaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answers_id', models.CharField(max_length=200)),
                ('submitted_ans_id', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('question_id', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('registration_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='registration.Registration')),
            ],
            options={
                'verbose_name_plural': 'Questionnaire Submit',
            },
        ),
    ]
