# Generated by Django 3.0.3 on 2020-03-22 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200322_0556'),
        ('exam', '0003_auto_20200322_0556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam_paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='exam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam', to='exam.Exam'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='professional',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='registration',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='registration.Registration'),
        ),
    ]
