
# Generated by Django 2.2.6 on 2019-11-25 09:44


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examinees', '0015_auto_20191116_1214'),
        ('questionnaire', '0003_auto_20191117_1426'),
        ('questionnaire', '0004_auto_20191123_1210'),
        ('questionnaire_submit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinees.Examinee')),
                ('questionnaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='questionnaire.Questionnaire')),
            ],
            options={
                'verbose_name_plural': 'Assign Questionnaire',
            },
        ),
    ]
