# Generated by Django 3.0.3 on 2020-03-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_paper', '0002_auto_20200322_0556'),
        ('exam_paper', '0002_auto_20200323_0700'),
    ]

    operations = [
    ]
