# Generated by Django 2.2.6 on 2019-12-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_submit', '0002_assignquestionnaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampaper',
            options={'verbose_name_plural': 'Exam Paper'},
        ),
    ]
