# Generated by Django 3.0.3 on 2020-03-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_paper', '0003_merge_20200324_0643'),
        ('exam_paper', '0003_merge_20200324_0618'),
    ]

    operations = [
    ]
