# Generated by Django 2.2.6 on 2019-12-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_examquestionnairedetails'),
        ('examinees', '0015_auto_20191116_1214'),
        ('questionnaire_submit', '0003_auto_20191201_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampaper',
            name='registration_id',
        ),
        migrations.AddField(
            model_name='exampaper',
            name='exam',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exams.Exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exampaper',
            name='examinee',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='examinee', to='examinees.Examinee'),
            preserve_default=False,
        ),
    ]
