# Generated by Django 2.2.6 on 2019-12-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinees', '0015_auto_20191116_1214'),
        ('exams', '0009_examquestionnairedetails'),
        ('question', '0014_merge_20191201_1521'),
        ('questionnaire_submit', '0004_auto_20191203_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exampaper',
            new_name='Exampapersubmition',
        ),
    ]
