# Generated by Django 2.2.6 on 2019-12-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20191201_1839'),
        ('questionnaire_submit', '0006_auto_20191203_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='registration',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='registration.Registration'),
            preserve_default=False,
        ),
    ]
