# Generated by Django 2.2.6 on 2019-12-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_submit', '0007_exampaper_registration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exampaper',
            table='exam_paper',
        ),
    ]
