# Generated by Django 3.0.3 on 2020-02-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='district',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='location.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='division',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='location.Division'),
            preserve_default=False,
        ),
    ]
