# Generated by Django 3.0.3 on 2020-02-05 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200205_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'industry',
                'verbose_name_plural': 'industries',
                'db_table': 'industry',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'JobType',
                'verbose_name_plural': 'JobTypes',
                'db_table': 'Job_type',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'db_table': 'Qualification',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('job_location', models.CharField(max_length=256)),
                ('experience', models.CharField(max_length=128)),
                ('salary_range', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(max_length=128)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('other_benefits', models.TextField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=128, null=True)),
                ('comapny_location', models.CharField(blank=True, max_length=128, null=True)),
                ('comapny_name', models.CharField(blank=True, max_length=128, null=True)),
                ('webaddress', models.CharField(blank=True, max_length=128, null=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.Industry')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.JobType')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.Qualification')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'job',
            },
        ),
    ]
