# Generated by Django 3.0.3 on 2020-04-13 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_merge_20200405_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.ForeignKey(db_column='company', default='', on_delete=django.db.models.deletion.PROTECT, to='job.Company'),
            preserve_default=False,
        ),
    ]
