# Generated by Django 3.0.3 on 2020-04-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_auto_20200413_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
    ]
